# Generated by Django 4.1.7 on 2023-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="vaccine_status",
            field=models.CharField(
                choices=[("1", "Vaccinated"), ("2", "Not Vaccinated")],
                default="1",
                max_length=20,
            ),
        ),
    ]
