# Generated by Django 4.1.7 on 2023-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_record_vaccine_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="vaccine_status",
            field=models.CharField(
                choices=[
                    ("Vaccinated", "Vaccinated"),
                    ("Not Vaccinated", "Not Vaccinated"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
